# Generated by Django 5.1.3 on 2024-11-12 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_likes_user_question_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='question',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='liked_questions', through='app.QuestionLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
